name: Debricked scan

on: 
  workflow_dispatch:

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      - uses: debricked/actions/resolve@v3
      - uses: debricked/actions@v3
        env:
           DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

          
        
