name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: debricked/actions@v3
      #   env:
      #     DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}

        # install fcli
      - run: |
          wget https://github.com/fortify/fcli/releases/download/v1.3.1/fcli-linux.tgz
          tar -xzvf fcli-linux.tgz
          fcli 
          
        
